### ISSUE TITLE
COOK_013 Add Recipes to Favorites

### ISSUE THREAD

**Issue by hana016** [sw20-tug/MA-Morning-3#29]
As a user wants to add or remove recipes to his favorite recipes by clicking a star button on the recipe cells.

Acceptance criteria:
- A clickable icon signalizes if a recipe is marked as favorite or not 
- The icon is toggle-able to change the status of the favorite  recipe
- When a recipe is marked as favorite, it gets displayed under the favorites tap
- When a recipe is removed from the favorites, it is no longer displayed under the favorites tab

**Comment by Lms24** [comment]
Also, the favorites tab should actually display an icon (say a star or something) that marks it as a favorits tab. The icon right now doesn't do that
