### ISSUE TITLE
COOK_004 Rename recipes

### ISSUE THREAD

**Issue by sw20-tugraz** [sw20-tug/MA-Morning-3#4]
As a user I want to be able to edit or rename existing recipes.

**Acceptance criteria:**
- It should be possible to rename an existing recipe
- Renaming means changing the title of the recipe
- This should be possible directly from the overview without going to another screen

**Comment by Lms24** [comment]
We decided to not implement this feature as from our point of view it does not make sense to add yet another edit possibility, albeit just one for renaming. The users have two options to edit and thereby also rename recipes once #9 is implemented: By long clicking a recipe or by clicking the edit icon in the detail view.

Closing this issue.
